# Generated by Django 5.0.3 on 2026-02-12 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='data_matricula',
        ),
    ]
